server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: Theodore1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecret
  expired:
    access: 1800
    refresh: 43200