server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_login
    username: root
    password: Theodore1@
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

jwt:
  secret: secret_key
  expired:
    access: 1800
    refresh: 43200