server:
  port: 8080

spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${SECRET}
  expired:
    access: ${ACCESS}
    refresh: ${REFRESH}